INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Funkdafied', 'Da Brat', 'music/rap/Da Brat - Funkdafied.mp3', 'rap', 2009);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('The Roots', 'What They DO', 'music/rap/The Roots - What They Do.mp3', 'rap', 2009);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Coolio', 'Gangstas Paradise', 'music/rap/Das EFX - What They Do.mp3', 'rap', 1995);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('ODB', 'Brooklyn Zoo', 'music/rap/ODB - Brooklyn Zoo.mp3', 'rap', 1995);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('GZA', 'Fame', 'music/rap/GZA - Fame.mp3', 'rap', 2010);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Xzibit', 'What U See Is What U Get', 'music/rap/Xzibit - What U See Is What U Get.mp3', 'rap', 1998);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('LUNIZ', 'I GOT 5 ON IT', 'music/rap/LUNIZ - I GOT 5 ON IT.mp3', 'rap', 1995);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Akrobatik', 'Remind my soul', 'music/rap/GZA - Fame.mp3', 'rap', 2003);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Ice Cube', 'It was a good day', 'music/rap/Ice Cube - It was a good day.mp3', 'rap', 1992);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Cypress Hill', 'How I Could Just Kill a Man', 'music/rap/Cypress Hill - How I Could Just Kill a Man.mp3', 'rap', 2011);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('The Game', 'Dreams', 'music/rap/The Game - Dreams.mp3', 'rap', 2004);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Fabolous', 'Breathe', 'music/rap/Fabolous - Breathe.mp3', 'rap', 2004);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Big L', 'Ebonics', 'music/rap/Big L - Ebonics.mp3', 'rap', 1998);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Snoop Dogg', 'Gin And Juice', 'music/rap/Snoop Dogg - Gin And Juice.mp3', 'rap', 1993);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Slum Village', 'Reunion', 'music/rap/Slum Village - Reunion.mp3', 'rap', 2004);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Special Ed', 'I Got It Made', 'music/rap/Special Ed - I Got It Made.mp3', 'rap', 1989);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Eminem', 'Mosh', 'music/rap/Eminem - Mosh.mp3', 'rap', 2004);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('DJ Quik', 'Tonite', 'music/rap/DJ Quik - Tonite.mp3', 'rap', 1991);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Kanye West', 'Jesus Walks', 'music/rap/Kanye West - Jesus Walks.mp3', 'rap', 2004);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Scarface', 'I Seen a Man Die', 'music/rap/Scarface - I Seen a Man Die.mp3', 'rap', 1994);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('DMX', 'Slippin', 'music/rap/DMX - Slippin.mp3', 'rap', 1998);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Mos Def', 'Mathematics', 'music/rap/Mos Def - Mathematics.mp3', 'rap', 1999);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Westside Connection', 'Mathematics', 'music/rap/Westside Connection - Bow Down.mp3', 'rap', 1999);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Warren G', 'Regulate', 'music/rap/Warren G - Regulate.mp3', 'rap', 1999);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Westside Connection', 'Bow Down', 'music/rap/Westside Connection - Bow Down.mp3', 'rap', 1996);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Brand Nubian', 'Slow Down', 'music/rap/Brand Nubian - Slow Down.mp3', 'rap', 1990);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Mobb Deep', 'Shook Ones, Pt. II.mp3', 'music/rap/Mobb Deep - Shook Ones, Pt. II', 'rap', 1995);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Kurtis Blow', 'The Breaks', 'music/rap/Kurtis Blow - The Breaks.mp3', 'rap', 1980);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Talib Kweli', 'Get By', 'music/rap/Talib Kweli - Get By.mp3', 'rap', 2002);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Beastie boys', 'Paul Revere', 'music/rap/Beastie boys - Paul Revere.mp3', 'rap', 1986);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Masked Wolf', 'Astronaut in the Ocean', 'music/rap/Masked Wolf - Astronaut in the Ocean.mp3', 'rap', 2019);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Cardi B', 'Up', 'music/rap/Cardi B - Up.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Trippie Redd', '1st Degree Murder', 'music/rap/Trippie Redd - 1st Degree Murder.mp3', 'rap', 2022);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Trippie Redd', 'BANG!', 'music/rap/Trippie Redd - BANG!.mp3', 'rap', 2018);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('SwaVay', 'GO SHORTY', 'music/rap/SwaVay - GO SHORTY.mp3', 'rap', 2018);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Polo G', 'RAPSTAR', 'music/rap/Polo G - RAPSTAR.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Lil Baby', 'On Me', 'music/rap/Lil Baby - On Me.mp3', 'rap', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Moneybagg Yo', 'Wockesha', 'music/rap/Moneybagg Yo - Wockesha.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('CJ', 'WHOOPTY', 'music/rap/CJ - WHOOPTY.mp3', 'rap', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Megan Thee Stallion', 'Body', 'music/rap/Megan Thee Stallion - Body.mp3', 'rap', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Roddy Ricch', 'Late At Night', 'music/rap/Roddy Ricch - Late At Night.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Drake', 'Knife Talk', 'music/rap/Drake - Knife Talk.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Yeat', 'Talk', 'music/rap/Yeat - Talk.mp3', 'rap', 2022);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Future', 'Mask Off', 'music/rap/Future - Mask Off.mp3', 'rap', 2017);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Eminem', 'Lose Yourself', 'music/rap/Eminem - Lose Yourself.mp3', 'rap', 2015);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Cardi B', 'Bodak Yellow', 'music/rap/Cardi B - Bodak Yellow.mp3', 'rap', 2017);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Geto Boys', 'Mind Playing Tricks On Me', 'music/rap/Geto Boys - Mind Playing Tricks On Me.mp3', 'rap', 2009);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('2Pac', 'Dear Mama', 'music/rap/2Pac - Dear Mama.mp3', 'rap', 2011);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Public Enemy', 'Fight The Power', 'music/rap/Public Enemy - Fight The Power.mp3', 'rap', 1989);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('The Notorious B.I.G.', 'Juicy', 'music/rap/The Notorious B.I.G. - Juicy.mp3', 'rap', 1994);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('De La Soul', 'Me,Mysel.mp3f,and,I', 'music/rap/De La Soul - Me,Myself,and,I', 'rap', 2011);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('JAY-Z', '99 Problems', 'music/rap/JAY-Z - 99 Problems.mp3', 'rap', 2011);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Nevi', 'Get Down', 'music/rap/Nevi - Get Down.mp3', 'rap', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Gnarls Barkley', 'Crazy', 'music/rap/Gnarls Barkley - Crazy.mp3', 'rap', 2009);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Rod Wave', 'Tombstone', 'music/rap/Rod Wave - Tombstone.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Jack Harlow', 'Tyler Herro', 'music/rap/Jack Harlow - Tyler Herro.mp3', 'rap', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Kanye West', 'Hurricane', 'music/rap/Kanye West - Hurricane.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Drake', 'Champagne Poetry', 'music/rap/Drake - Champagne Poetry.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Erica Banks', 'Buss It', 'music/rap/Erica Banks - Buss It.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('50 Cent', 'In Da Club', 'music/rap/50 Cent - In Da Club.mp3', 'rap', 2009);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Drake', 'In My Feelings', 'music/rap/Drake - In My Feelings.mp3', 'rap', 2018);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Ice Cube', 'It Was A Good Day', 'music/rap/Ice Cube - It Was A Good Day.mp3', 'rap', 2018);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('The Notorious B.I.G.', 'Hypnotize', 'music/rap/The Notorious B.I.G. - Hypnotize.mp3', 'rap', 2018);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Wu-Tang Clan', 'C.R.E.A.M.', 'music/rap/Wu-Tang Clan - C.R.E.A.M..mp3', 'rap', 1983);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Drake', 'No Friends In The Industry', 'music/rap/Drake - No Friends In The Industry.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Rod Wave', 'Street Runner', 'music/rap/Rod Wave - Street Runner.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Roddy Ricch', 'Stop Breathing', 'music/rap/Roddy Ricch - Stop Breathing.mp3', 'rap', 2021);

INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Instrumenti', 'Lena Uguns', 'music/latvian/Instrumenti - Lena Uguns.mp3', 'latvian', 2015);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Jumprava', 'Ziemelmeita', 'music/latvian/Jumprava - Ziemelmeita.mp3', 'latvian', 2007);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Jumprava', 'Ziemelmeita', 'music/latvian/Dzeltenie Pastnieki - Nac ara no adens.mp3', 'latvian', 1982);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Prata Vetra', 'Tavas Majas Mana Azote', 'music/latvian/Prata Vetra - Tavas Majas Mana Azote.mp3', 'latvian', 2014);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('100 Debija', 'Man dimantu nav', 'music/latvian/100 Debija - Man dimantu nav.mp3', 'latvian', 1995);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('BERMUDU DIVSTURIS', 'SARKANBALTSARKANAIS', 'music/latvian/BERMUDU DIVSTURIS - SARKANBALTSARKANAIS.mp3', 'latvian', 2019);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('BERMUDU DIVSTURIS', 'Ne man GUCCI, ne man NIKE.mp3', 'music/latvian/BERMUDU DIVSTURIS - Ne man GUCCI, ne man NIKE', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Singapuras Satins', 'Blingi', 'music/latvian/Singapuras Satins - Blingi.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Aminata', 'Pamet mani', 'music/latvian/Aminata - Pamet mani.mp3', 'latvian', 2019);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Aija Andrejeva', 'Pamet mani', 'music/latvian/Aija Andrejeva - LAIME SI.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('BERMUDU DIVSTURIS', 'PONTA PEC', 'music/latvian/BERMUDU DIVSTURIS - PONTA PEC.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Dons', 'Ilgoties man nesanak', 'music/latvian/Dons - Ilgoties man nesanak.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Exact', 'Unlucky Loki', 'music/latvian/Exact - Unlucky Loki.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('MESA', 'Man nav bail', 'music/latvian/MESA - Man nav bail.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('MESA', 'Tuvak Tev', 'music/latvian/MESA - Tuvak Tev.mp3', 'latvian', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('MESA', 'Man nav bail', 'music/latvian/MESA - Man nav bail.mp3', 'latvian', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Urbanstep', 'Take Apart The Sky', 'music/latvian/Urbanstep - Take Apart The Sky.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Edavardi', 'Spoki', 'music/latvian/Edavardi - Spoki.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Rassell', 'Skrien cauri dzivei', 'music/latvian/Rassell - Skrien cauri dzivei.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Eliots', 'Carguru', 'music/latvian/Eliots - Carguru.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Markus Riva', 'Vienmer', 'music/latvian/Markus Riva - Vienmer.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Fakts', 'Karantinas Bluzs', 'music/latvian/Fakts - Karantinas Bluzs.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Markus Riva', 'Melns Vai Balts', 'music/latvian/Markus Riva - Melns Vai Balts.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('TAVS KAROGS', 'The Sound Poets', 'music/latvian/TAVS KAROGS - T-he Sound Poets.mp3', 'latvian', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Kreisais Krasts', 'Vardu Piegade', 'music/latvian/Kreisais Krasts - Vardu Piegade.mp3', 'latvian', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Aminata', 'Uz neatklatam zvaigznem', 'music/latvian/Aminata - Uz neatklatam zvaigznem.mp3', 'latvian', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Dzelzs Vilks', 'AIZLIEGUMI LIKUMI', 'music/latvian/Dzelzs Vilks - AIZLIEGUMI LIKUMI.mp3', 'latvian', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Martins Ruskis', 'Mes nepagursim', 'music/latvian/Martins Ruskis - Mes nepagursim.mp3', 'latvian', 2012);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Prata Vetra', 'Ko tu doma', 'music/latvian/Prata Vetra - Ko tu doma.mp3', 'latvian', 2012);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('GACHO', 'Stampa Gridu', 'music/latvian/GACHO - Stampa Gridu.mp3', 'latvian', 2012);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Prata Vetra', 'Lantern', 'music/latvian/Prata Vetra - Lantern.mp3', 'latvian', 2012);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Audience Killers', 'The Runaway Kite', 'music/latvian/Audience Killers - The Runaway Kite.mp3', 'latvian', 2011);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('MELLENDIG', 'Say IT', 'music/latvian/MELLENDIG - Say It.mp3', 'latvian', 2012);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Prata vetra', 'Mana dziesma', 'music/latvian/Prata vetra - Mana dziesma.mp3', 'latvian', 2018);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('AEiropa', 'Tuvuma Taluma', 'music/latvian/AEiropa - Tuvuma Taluma.mp3', 'latvian', 2016);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('MUSIQQ', 'DARI KA ES', 'music/latvian/MUSIQQ - DARI KA ES.mp3', 'latvian', 2013);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('MUSIQQ', 'Silta Sirds', 'music/latvian/MUSIQQ - Silta Sirds.mp3', 'latvian', 2013);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('INTARS BUSULIS', 'MIGLAS RITS', 'music/latvian/INTARS BUSULIS - MIGLAS RITS.mp3', 'latvian', 2016);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Dons', 'Pedeja vestule', 'music/latvian/Dons - Pedeja vestule.mp3', 'latvian', 2014);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Dons', 'Pasa ielas gala', 'music/latvian/Dons - Pasa ielas gala.mp3', 'latvian', 2014);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Ivo Fomins', 'Tu man esi', 'music/latvian/Ivo Fomins - Tu man esi.mp3', 'latvian', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('OZOLS', 'Tu Tikai Doma par Sevi', 'music/latvian/OZOLS - Tu Tikai Doma par Sevi.mp3', 'latvian', 2022);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('OZOLS', 'Tevis Blakus Nav', 'music/latvian/OZOLS - Tevis Blakus Nav.mp3', 'latvian', 2022);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('APVEDCELS', 'ZEMENES', 'music/latvian/APVEDCELS - ZEMENES.mp3', 'latvian', 2012);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Brugis', 'Kaija', 'music/latvian/Brugis - Kaija.mp3', 'latvian', 2008);

INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('THE LONELIEST', 'Maneskin', 'music/rock/Maneskin - THE LONELIEST.mp3', 'rock', 2022);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Dream on', 'Aerosmith', 'music/rock/Aerosmith - Dream on.mp3', 'rock', 1973);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Paint It, Black', 'The Rolling Stones', 'music/rock/The Rolling Stones - Paint It, Black.mp3', 'rock', 1966);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Zombie', 'The Cranberries', 'music/rock/The Cranberries - Zombie.mp3', 'rock', 1994);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('I Was Made For Lovin'' You', 'Kiss', 'music/rock/Kiss - I Was Made For Lovin'' You.mp3', 'rock', 1979);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Sweet Child O'' Mine', 'Guns and Roses', 'music/rock/Guns and Roses - Sweet Child O'' Mine.mp3', 'rock', 1987);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Your Love', 'Outfield', 'music/rock/Outfield - Your Love.mp3', 'rock', 1985);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Bring me to life', 'Evanescence', 'music/rock/Evanescence - Bring me to life.mp3', 'rock', 2003);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Every Breath You Take', 'The Police', 'music/rock/The Police - Every Breath You Take.mp3', 'rock', 1983);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Don''t Stop Believin''', 'Journey', 'music/rock/Journey - Don''t Stop Believin''.mp3', 'rock', 1981);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Nothing''s Gonna Stop Us Now', 'Starship', 'music/rock/Starship - Nothing''s Gonna Stop Us Now.mp3', 'rock', 1987);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Highway To Hell', 'AC DC', 'music/rock/AC DC - Highway To Hell.mp3', 'rock', 1979);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Eye Of The Tiger', 'Survivor', 'music/rock/Survivor - Eye Of The Tiger.mp3', 'rock', 1982);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('November Rain', 'Guns and Roses', 'music/rock/Guns and Roses - November Rain.mp3', 'rock', 1991);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('The Final Countdown', 'Europe', 'music/rock/Europe - The Final Countdown.mp3', 'rock', 1986);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('How You Remind Me', 'Nickelback', 'music/rock/Nickelback - How You Remind Me.mp3', 'rock', 2001);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('I Don''t Want to Miss a Thing', 'Aerosmith', 'music/rock/Aerosmith - I Don''t Want to Miss a Thing.mp3', 'rock', 1998);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Thunderstruck', 'AC DC', 'music/rock/AC DC - Thunderstruck.mp3', 'rock', 1990);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('In The End', 'Linkin Park', 'music/rock/Linkin Park - In The End.mp3', 'rock', 2001);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Can You Feel My Heart', 'Bring Me The Horizon', 'music/rock/Bring Me The Horizon - Can You Feel My Heart.mp3', 'rock', 2013);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Bad To The Bone', 'George Thorogood, The Destroyers', 'music/rock/George Thorogood, The Destroyers - Bad To The Bone.mp3', 'rock', 1982);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Wherever You Will Go', 'The Calling', 'music/rock/The Calling - Wherever You Will Go.mp3', 'rock', 2001);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Live Wire', 'AC DC', 'music/rock/AC DC - Live Wire.mp3', 'rock', 1975);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('With Or Without You', 'U2', 'music/rock/U2 - With Or Without You.mp3', 'rock', 1987);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Don''t Look Back In Anger', 'Oasis', 'music/rock/Oasis - Don''t Look Back In Anger.mp3', 'rock', 1995);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Back In Black', 'AC DC', 'music/rock/AC DC - Back In Black.mp3', 'rock', 1980);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Another Brick In the Wall', 'Pink Floyd', 'music/rock/Pink Floyd - Another Brick In the Wall, Pt. 2.mp3', 'rock', 1979);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('She Keeps Me Up', 'Nickelback', 'music/rock/Nickelback - She Keeps Me Up.mp3', 'rock', 2014);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Another One Bites the Dust', 'Queen', 'music/rock/Queen - Another One Bites the Dust.mp3', 'rock', 1980);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('How to Save a Life', 'The Fray', 'music/rock/The Fray - How to Save a Life.mp3', 'rock', 2005);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('I Love Rock ’N Roll', 'Joan Jett, The Blackhearts', 'music/rock/Joan Jett, The Blackhearts — I Love Rock ’N Roll.mp3', 'rock', 1981);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Bones', 'Imagine Dragons', 'music/rock/Imagine Dragons - Bones.mp3', 'rock', 2022);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Smells Like Teen Spirit', 'Nirvana', 'music/rock/Nirvana - Smells Like Teen Spirit.mp3', 'rock', 1991);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Believer', 'Imagine Dragons', 'music/rock/Imagine Dragons - Believer.mp3', 'rock', 2017);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Stairway To Heaven', 'Led Zeppelin', 'music/rock/Led Zeppelin - Stairway To Heaven.mp3', 'rock', 1971);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Smoke On The Water', 'Deep Purple', 'music/rock/Deep Purple - Smoke On The Water.mp3', 'rock', 1972);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Can''t Stop', 'Red Hot Chili Peppers', 'music/rock/Red Hot Chili Peppers - Can''t Stop.mp3', 'rock', 2002);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('I Hate Everything About You', 'Three Days Grace', 'music/rock/Three Days Grace - I Hate Everything About You.mp3', 'rock', 2003);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Burn It Down', 'Linkin Park', 'music/rock/Linkin Park - Burn It Down.mp3', 'rock', 2012);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Iris', 'Goo Goo Dolls', 'music/rock/Goo Goo Dolls - Iris.mp3', 'rock', 1998);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Monster', 'Skillet', 'music/rock/Skillet - Monster.mp3', 'rock', 2009);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Centuries', 'Fall Out Boy', 'music/rock/Fall Out Boy - Centuries.mp3', 'rock', 2014);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('All stars', 'Smash Mouth', 'music/rock/Smash Mouth - All stars.mp3', 'rock', 1999);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Fuel', 'Metallica', 'music/rock/Metallica - Fuel.mp3', 'rock', 1997);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Du Hast', 'Rammstein', 'music/rock/Rammstein - Du Hast.mp3', 'rock', 1997);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Way Down We Go', 'Kaleo', 'music/rock/Kaleo - Way Down We Go.mp3', 'rock', 2015);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Seven Nation Army', 'The White Stripes', 'music/rock/The White Stripes - Seven Nation Army.mp3', 'rock', 2003);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Welcome To The Jungle', 'Guns and Roses', 'music/rock/Guns and Roses - Welcome To The Jungle.mp3', 'rock', 1987);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('I Dont Want To Miss A Thing', 'Aerosmith', 'music/rock/Aerosmith - I Dont Want To Miss A Thing.mp3', 'rock', 1998);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('We Will Rock You', 'Queen', 'music/rock/Queen - We Will Rock You.mp3', 'rock', 1977);

INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Levitating', 'Dua Lipa', 'music/pop/Dua Lipa - Levitating.mp3', 'pop', 2020);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Unholy', 'Sam Smith, Kim Petras', 'music/pop/Sam Smith, Kim Petras - Unholy.mp3', 'pop', 2022);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Miss You', 'Oliver Tree, Robin Schulz', 'music/pop/Oliver Tree, Robin Schulz - Miss You.mp3', 'pop', 2022);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Say My Name', 'David Guetta, Bebe Rexha, J Balvin', 'music/pop/David Guetta, Bebe Rexha, J Balvin - Say My Name.mp3', 'pop', 2022);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Snap', 'Rosa Linn', 'music/pop/Rosa Linn - Snap.mp3', 'pop', 2022);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Another Love', 'Tom Odell', 'music/pop/Tom Odell - Another Love.mp3', 'pop', 2022);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('As It Was', 'Harry Styles', 'music/pop/Harry Styles - As It Was.mp3', 'pop', 2022);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Until I Found You', 'Stephen Sanchez', 'music/pop/Stephen Sanchez - Until I Found You.mp3', 'pop', 2022);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Unstoppable', 'Sia', 'music/pop/Sia - Unstoppable.mp3', 'pop', 2016);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Lonely Ones', 'Lova', 'music/pop/Lova - Lonely Ones.mp3', 'pop', 2021);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Under The Influence', 'Chris Brown', 'music/pop/Chris Brown - Under The Influence.mp3', 'pop', 2019);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Middle of the night', 'Elley Duhé', 'music/pop/Elley Duhé - Middle of the night.mp3', 'pop', 2020);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Heat Waves', 'Glass Animals', 'music/pop/Glass Animals - Heat Waves.mp3', 'pop', 2020);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Cold Heart', 'Dua Lipa, Elton John', 'music/pop/Dua Lipa, Elton John - Cold Heart.mp3', 'pop', 2021);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Somewhere only we know', 'Keane', 'music/pop/Keane - Somewhere only we know.mp3', 'pop', 2004);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Sweater Weather', 'The Neighbourhood', 'music/pop/The Neighbourhood - Sweater Weather.mp3', 'pop', 2013);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Lovely', 'Billie Eilish, Khalid', 'music/pop/Billie Eilish, Khalid - Lovely.mp3', 'pop', 2018);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Love on the Brain', 'Rihanna', 'music/pop/Rihanna - Love on the Brain.mp3', 'pop', 2016);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Somebody That I Used To Know', 'Gotye, Kimbra', 'music/pop/Gotye - Somebody That I Used To Know.mp3', 'pop', 2016);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Perfect', 'Ed Sheeran', 'music/pop/Ed Sheeran - Perfect.mp3', 'pop', 2017);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Set Fire to the Rain', 'Adele', 'music/pop/Adele - Set Fire to the Rain.mp3', 'pop', 2021);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Blinding Lights', 'The Weeknd', 'music/pop/The Weeknd - Blinding Lights.mp3', 'pop', 2019);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Infinity', 'Jaymes Young', 'music/pop/Jaymes Young - Infinity.mp3', 'pop', 2017);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Let Her Go', 'Passenger', 'music/pop/Passenger - Let Her Go.mp3', 'pop', 2012);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('STAY', 'The Kid Laroi, Justin Bieber', 'music/pop/The Kid Laroi, Justin Bieber - STAY.mp3', 'pop', 2021);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Kiss me more', 'Doja Cat, SZA', 'music/pop/Doja Cat, SZA - Kiss me more.mp3', 'pop', 2021);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Good 4 u', 'Olivia Rodrigo', 'music/pop/Olivia Rodrigo - Good 4 u.mp3', 'pop', 2021);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('MONTERO', 'Lil Nas X', 'music/pop/Lil Nas X — MONTERO.mp3', 'pop', 2021);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Leave The Door Open', 'Bruno Mars, Anderson .Paak, Silk Sonic', 'music/pop/Bruno Mars, Anderson .Paak, Silk Sonic - Leave The Door Open.mp3', 'pop', 2021);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Drivers license', 'Olivia Rodrigo', 'music/pop/Olivia Rodrigo - Drivers license.mp3', 'pop', 2020);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Peaches', 'Justin Bieber, Daniel Caesar, GIVĒON', 'music/pop/Justin Bieber, Daniel Caesar, GIVĒON - Peaches.mp3', 'pop', 2021);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Bad habits', 'Ed Sheeran', 'music/pop/Ed Sheeran - Bad habits.mp3', 'pop', 2020);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Deja Vu', 'Olivia Rodrigo', 'music/pop/Olivia Rodrigo - Deja Vu.mp3', 'pop', 2021);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Butter', 'BTS', 'music/pop/BTS - Butter.mp3', 'pop', 2021);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Positions', 'Ariana Grande', 'music/pop/Ariana Grande - Positions.mp3', 'pop', 2020);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('You Right', 'Doja Cat, The Weeknd', 'music/pop/Doja Cat, The Weeknd - You Right.mp3', 'pop', 2021);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Without You', 'The Kid Laroi', 'music/pop/The Kid Laroi - Without You.mp3', 'pop', 2020);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Old Town Road', 'Lil Nas X', 'music/pop/Lil Nas X  - Old Town Road.mp3', 'pop', 2019);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Without me', 'Halsey', 'music/pop/Halsey - Without me.mp3', 'pop', 2019);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Despacito', 'Luis Fonsi, Daddy Yankee, Justin Biber', 'music/pop/Luis Fonsi, Daddy Yankee, Justin Biber - Despacito.mp3', 'pop', 2017);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Rolling In The Deep', 'Adele', 'music/pop/Adele - Rolling In The Deep.mp3', 'pop', 2011);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Happier', 'Marshmello, Bastille', 'music/pop/Marshmello, Bastille - Happier.mp3', 'pop', 2018);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Call Me Maybe', 'Carly Rae Jepsen', 'music/pop/Carly Rae Jepsen - Call Me Maybe.mp3', 'pop', 2012);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Royals', 'Lorde', 'music/pop/Lorde – Royals.mp3', 'pop', 2013);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Moves Like Jagger', 'Maroon 5, Christina Aguilera', 'music/pop/Maroon 5, Christina Aguilera - Moves Like Jagger.mp3', 'pop', 2011);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Bad Guy', 'Billie Eilish', 'music/pop/Billie Eilish - Bad Guy.mp3', 'pop', 2019);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Happy', 'Pharrell Williams', 'music/pop/Pharrell Williams - Happy.mp3', 'pop', 2013);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Cant Stop The Feeling', 'Justin Timberlake', 'music/pop/Justin Timberlake - Cant Stop The Feeling.mp3', 'pop', 2016);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('All of me', 'John Legend', 'music/pop/John Legend - All of me.mp3', 'pop', 2014);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Shake it off', 'Taylor Swift', 'music/pop/Taylor Swift - Shake it off.mp3', 'pop', 2014);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('One more night', 'Maroon 5', 'music/pop/Maroon 5 - One more night.mp3', 'pop', 2012);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Love yourself', 'Justin Bieber', 'music/pop/Justin Bieber - Love yourself.mp3', 'pop', 2016);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('We Are Young', 'Fun, Janelle Monae', 'music/pop/Fun, Janelle Monae - We Are Young.mp3', 'pop', 2012);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Sucker', 'Jonas Brothers', 'music/pop/Jonas Brothers - Sucker.mp3', 'pop', 2019);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('All about that bass', 'Meghan Trainor', 'music/pop/Meghan Trainor - All about that bass.mp3', 'pop', 2014);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('STAY WITH ME', 'Sam Smith', 'music/pop/Sam Smith - STAY WITH ME.mp3', 'pop', 2015);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Wake Me Up', 'Avicii', 'music/pop/Avicii - Wake Me Up.mp3', 'pop', 2013);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Roar', 'Katy Perry', 'music/pop/Katy Perry - Roar.mp3', 'pop', 2013);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Adore you', 'Harry Styles', 'music/pop/Harry Styles - Adore you.mp3', 'pop', 2019);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Somone You Loved', 'Lewis Capaldi', 'music/pop/Lewis Capaldi - Somone You Loved.mp3', 'pop', 2019);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Dynamite', 'BTS', 'music/pop/BTS - Dynamite.mp3', 'pop', 2020);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Break my heart', 'Dua Lipa', 'music/pop/Dua Lipa - Break my heart.mp3', 'pop', 2020);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Rain On Me', 'Lady Gaga, Ariana Grande', 'music/pop/Lady Gaga, Ariana Grande - Rain On Me.mp3', 'pop', 2020);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Lush Life', 'Zara Larsson', 'music/pop/Zara Larsson - Lush Life.mp3', 'pop', 2015);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Save Your Tears', 'The Weeknd', 'music/pop/The Weeknd - Save Your Tears.mp3', 'pop', 2020);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('What Is Love', 'Haddaway', 'music/pop/Haddaway - What Is Love.mp3', 'pop', 1993);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Hymn for the weekend', 'Coldplay', 'music/pop/Coldplay - Hymn for the weekend.mp3', 'pop', 2015);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('I Ain''t Worried', 'OneRepublic', 'music/pop/OneRepublic - I Ain''t Worried.mp3', 'pop', 2022);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Hold My Hand', 'Lady Gaga', 'music/pop/Lady Gaga - Hold My Hand.mp3', 'pop', 2022);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Arcade', 'Duncan Laurence', 'music/pop/Duncan Laurence - Arcade.mp3', 'pop', 2020);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Get Lucky', 'Daft Punk, Pharrell Williams, Nile Rodgers', 'music/pop/Daft Punk, Pharrell Williams, Nile Rodgers - Get Lucky.mp3', 'pop', 2013);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Beggin''', 'Maneskin', 'music/pop/Måneskin - Beggin''.mp3', 'pop', 2017);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Let Me Down Slowly', 'Alec Benjamin', 'music/pop/Alec Benjamin - Let Me Down Slowly.mp3', 'pop', 2018);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Dusk Till Dawn', 'Zayn Malik, Sia', 'music/pop/Zayn Malik, Sia - Dusk Till Dawn.mp3', 'pop', 2018);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Cure For Me', 'AURORA', 'music/pop/AURORA - Cure For Me.mp3', 'pop', 2021);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Stayin Alive', 'The Bee Gees', 'music/pop/The Bee Gees - Stayin Alive.mp3', 'pop', 1977);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Locked out of Heaven', 'Bruno Mars', 'music/pop/Bruno Mars - Locked out of Heaven.mp3', 'pop', 2017);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Don''t Be So Shy', 'Imany', 'music/pop/Imany - Don''t Be So Shy.mp3', 'pop', 2014);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Lights', 'Ellie Goulding', 'music/pop/Ellie Goulding - Lights.mp3', 'pop', 2010);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Im Not The Only One', 'Sam Smith', 'music/pop/Sam Smith - Im Not The Only One.mp3', 'pop', 2014);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Love Me Again', 'John Newman', 'music/pop/John Newman - Love Me Again.mp3', 'pop', 2013);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Lay All Your Love On Me', 'Abba', 'music/pop/Abba - Lay All Your Love On Me.mp3', 'pop', 1980);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Theres Nothing Holdin Me Back', 'Shawn Mendes', 'music/pop/Shawn Mendes - Theres Nothing Holdin Me Back.mp3', 'pop', 2016);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Leave Before You Love Me', 'Marshmello, Jonas Brothers', 'music/pop/Marshmello, Jonas Brothers - Leave Before You Love Me.mp3', 'pop', 2021);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Love Me Like You Do', 'Ellie Goulding', 'music/pop/Ellie Goulding - Love Me Like You Do.mp3', 'pop', 2015);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Cheap Thrills', 'Sia', 'music/pop/Sia - Cheap Thrills.mp3', 'pop', 2016);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Sunroof', 'Nicky Youre, dazy', 'music/pop/Nicky Youre, dazy - Sunroof.mp3', 'pop', 2022);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('RASPUTIN', 'BONEY M.', 'music/pop/BONEY M. - RASPUTIN.mp3', 'pop', 1978);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Thriller', 'Michael Jackson', 'music/pop/Michael Jackson - Thriller.mp3', 'pop', 1982);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('BREAK MY SOUL', 'Beyonce', 'music/pop/Beyonce - BREAK MY SOUL.mp3', 'pop', 2022);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Beat It', 'Michael Jackson', 'music/pop/Michael Jackson - Beat It.mp3', 'pop', 1982);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('PHOTOGRAPH', 'Ed Sheeran', 'music/pop/Ed Sheeran - PHOTOGRAPH.mp3', 'pop', 2014);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Lady', 'Modjo', 'music/pop/Modjo - Lady.mp3', 'pop', 2000);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Crazy', 'Gnarls Barkley', 'music/pop/Gnarls Barkley - Crazy.mp3', 'pop', 2006);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Poker Face', 'Lady Gaga', 'music/pop/Lady Gaga - Poker Face.mp3', 'pop', 2008);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Chandelier', 'Sia', 'music/pop/Sia - Chandelier.mp3', 'pop', 2014);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Kings, Queens', 'Ava Max', 'music/pop/Ava Max - Kings, Queens.mp3', 'pop', 2020);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('We Found Love', 'Rihanna, Calvin Harris', 'music/pop/Rihanna, Calvin Harris - We Found Love.mp3', 'pop', 2011);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('The House Of The Rising Sun', 'The Animals', 'music/pop/The Animals - The House Of The Rising Sun.mp3', 'pop', 1964);
INSERT INTO songs (song_name, song_author, song_path, song_genre, song_year) VALUES ('Nothing Breaks Like A Heart', 'Mark Ronson, Miley Cyrus', 'music/pop/Mark Ronson, Miley Cyrus - Nothing Breaks Like A Heart.mp3', 'pop', 2019);