INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Funkdafied', 'Da Brat', 'music/rap/Da Brat - Funkdafied.mp3', 'rap', 2009);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('The Roots', 'What They DO', 'music/rap/The Roots - What They Do.mp3', 'rap', 2009);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Coolio', 'Gangstas Paradise', 'music/rap/Das EFX - What They Do.mp3', 'rap', 1995);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('ODB', 'Brooklyn Zoo', 'music/rap/ODB - Brooklyn Zoo.mp3', 'rap', 1995);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('GZA', 'Fame', 'music/rap/GZA - Fame.mp3', 'rap', 2010);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Xzibit', 'What U See Is What U Get', 'music/rap/Xzibit - What U See Is What U Get.mp3', 'rap', 1998);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('LUNIZ', 'I GOT 5 ON IT', 'music/rap/LUNIZ - I GOT 5 ON IT.mp3', 'rap', 1995);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Akrobatik', 'Remind my soul', 'music/rap/GZA - Fame.mp3', 'rap', 2003);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Ice Cube', 'It was a good day', 'music/rap/Ice Cube - It was a good day.mp3', 'rap', 1992);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Cypress Hill', 'How I Could Just Kill a Man', 'music/rap/Cypress Hill - How I Could Just Kill a Man.mp3', 'rap', 2011);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('The Game', 'Dreams', 'music/rap/The Game - Dreams.mp3', 'rap', 2004);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Fabolous', 'Breathe', 'music/rap/Fabolous - Breathe.mp3', 'rap', 2004);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Big L', 'Ebonics', 'music/rap/Big L - Ebonics.mp3', 'rap', 1998);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Snoop Dogg', 'Gin And Juice', 'music/rap/Snoop Dogg - Gin And Juice.mp3', 'rap', 1993);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Slum Village', 'Reunion', 'music/rap/Slum Village - Reunion.mp3', 'rap', 2004);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Special Ed', 'I Got It Made', 'music/rap/Special Ed - I Got It Made.mp3', 'rap', 1989);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Eminem', 'Mosh', 'music/rap/Eminem - Mosh.mp3', 'rap', 2004);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('DJ Quik', 'Tonite', 'music/rap/DJ Quik - Tonite.mp3', 'rap', 1991);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Kanye West', 'Jesus Walks', 'music/rap/Kanye West - Jesus Walks.mp3', 'rap', 2004);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Scarface', 'I Seen a Man Die', 'music/rap/Scarface - I Seen a Man Die.mp3', 'rap', 1994);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('DMX', 'Slippin', 'music/rap/DMX - Slippin.mp3', 'rap', 1998);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Mos Def', 'Mathematics', 'music/rap/Mos Def - Mathematics.mp3', 'rap', 1999);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Westside Connection', 'Mathematics', 'music/rap/Westside Connection - Bow Down.mp3', 'rap', 1999);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Warren G', 'Regulate', 'music/rap/Warren G - Regulate.mp3', 'rap', 1999);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Westside Connection', 'Bow Down', 'music/rap/Westside Connection - Bow Down.mp3', 'rap', 1996);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Brand Nubian', 'Slow Down', 'music/rap/Brand Nubian - Slow Down.mp3', 'rap', 1990);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Mobb Deep', 'Shook Ones, Pt. II', 'music/rap/Mobb Deep - Shook One.mp3s, Pt. II', 'rap', 1995);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Kurtis Blow', 'The Breaks', 'music/rap/Kurtis Blow - The Breaks.mp3', 'rap', 1980);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Talib Kweli', 'Get By', 'music/rap/Talib Kweli - Get By.mp3', 'rap', 2002);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Beastie boys', 'Paul Revere', 'music/rap/Beastie boys - Paul Revere.mp3', 'rap', 1986);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Masked Wolf', 'Astronaut in the Ocean', 'music/rap/Masked Wolf - Astronaut in the Ocean.mp3', 'rap', 2019);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Cardi B', 'Up', 'music/rap/Cardi B - Up.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Trippie Redd', '1st Degree Murder', 'music/rap/Trippie Redd – 1st Degree Murder.mp3', 'rap', 2022);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Trippie Redd', 'BANG!', 'music/rap/Trippie Redd – BANG!.mp3', 'rap', 2018);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('SwaVay', 'GO SHORTY', 'music/rap/SwaVay - GO SHORTY.mp3', 'rap', 2018);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Polo G', 'RAPSTAR', 'music/rap/Polo G - RAPSTAR.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Lil Baby', 'On Me', 'music/rap/Lil Baby - On Me.mp3', 'rap', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Moneybagg Yo', 'Wockesha', 'music/rap/Moneybagg Yo - Wockesha.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('CJ', 'WHOOPTY', 'music/rap/CJ - WHOOPTY.mp3', 'rap', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Megan Thee Stallion', 'Body', 'music/rap/Megan Thee Stallion - Body.mp3', 'rap', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Roddy Ricch', 'Late At Night', 'music/rap/Roddy Ricch - Late At Night.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Drake', 'Knife Talk', 'music/rap/Drake - Knife Talk.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Yeat', 'Talk', 'music/rap/Yeat - Talk.mp3', 'rap', 2022);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Future', 'Mask Off', 'music/rap/Future - Mask Off.mp3', 'rap', 2017);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Eminem', 'Lose Yourself', 'music/rap/Eminem - Lose Yourself.mp3', 'rap', 2015);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Cardi B', 'Bodak Yellow', 'music/rap/Cardi B - Bodak Yellow.mp3', 'rap', 2017);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Geto Boys', 'Mind Playing Tricks On Me', 'music/rap/Geto Boys - Mind Playing Tricks On Me.mp3', 'rap', 2009);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('2Pac', 'Dear Mama', 'music/rap/2Pac - Dear Mama.mp3', 'rap', 2011);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Public Enemy', 'Fight The Power', 'music/rap/Public Enemy - Fight The Power.mp3', 'rap', 1989);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('The Notorious B.I.G.', 'Juicy', 'music/rap/The Notorious B.I.G. - Juicy.mp3', 'rap', 1994);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('De La Soul', 'Me,Myself,and,I', 'music/rap/De La Soul - M.mp3e,Myself,and,I', 'rap', 2011);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('JAY-Z', '99 Problems', 'music/rap/JAY-Z - 99 Problems.mp3', 'rap', 2011);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Nevi', 'Get Down', 'music/rap/Nevi - Get Down.mp3', 'rap', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Gnarls Barkley', 'Crazy', 'music/rap/Gnarls Barkley - Crazy.mp3', 'rap', 2009);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Rod Wave', 'Tombstone', 'music/rap/Rod Wave - Tombstone.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Jack Harlow', 'Tyler Herro', 'music/rap/Jack Harlow - Tyler Herro.mp3', 'rap', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Kanye West', 'Hurricane', 'music/rap/Kanye West - Hurricane.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Drake', 'Champagne Poetry', 'music/rap/Drake - Champagne Poetry.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Erica Banks', 'Buss It', 'music/rap/Erica Banks - Buss It.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('50 Cent', 'In Da Club', 'music/rap/50 Cent - In Da Club.mp3', 'rap', 2009);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Drake', 'In My Feelings', 'music/rap/Drake - In My Feelings.mp3', 'rap', 2018);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Ice Cube', 'It Was A Good Day', 'music/rap/Ice Cube - It Was A Good Day.mp3', 'rap', 2018);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('The Notorious B.I.G.', 'Hypnotize', 'music/rap/The Notorious B.I.G. - Hypnotize.mp3', 'rap', 2018);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Wu-Tang Clan', 'C.R.E.A.M.', 'music/rap/Wu-Tang Clan - C.R.E.A.M..mp3', 'rap', 1983);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Drake', 'No Friends In The Industry', 'music/rap/Drake - No Friends In The Industry.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Rod Wave', 'Street Runner', 'music/rap/Rod Wave - Street Runner.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Roddy Ricch', 'Stop Breathing', 'music/rap/Roddy Ricch - Stop Breathing.mp3', 'rap', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Instrumenti', 'Lena Uguns', 'music/latvian/Instrumenti - Lena Uguns.mp3', 'latvian', 2015);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Jumprava', 'Ziemelmeita', 'music/latvian/Jumprava - Ziemelmeita.mp3', 'latvian', 2007);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Jumprava', 'Ziemelmeita', 'music/latvian/Dzeltenie Pastnieki - Nac ara no adens.mp3', 'latvian', 1982);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Prata Vetra', 'Tavas Majas Mana Azote', 'music/latvian/Prata Vetra - Tavas Majas Mana Azote.mp3', 'latvian', 2014);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('100 Debija', 'Man dimantu nav', 'music/latvian/100 Debija - Man dimantu nav.mp3', 'latvian', 1995);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('BERMUDU DIVSTURIS', '#SARKANBALTSARKANAIS', 'music/latvian/BERMUDU DIVSTŪRIS - #SARKANBALTSARKANAIS.mp3', 'latvian', 2019);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('BERMUDU DIVSTURIS', 'Ne man GUCCI, ne man NIKE', 'music/latvian/BERMUDU DIVSTŪRIS - Ne man GUCC.mp3I, ne man NIKE', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Singapuras Satins', 'Blingi', 'music/latvian/Singapuras Satins - Blingi.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Aminata', 'Pamet mani', 'music/latvian/Aminata - Pamet mani.mp3', 'latvian', 2019);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Aija Andrejeva', 'Pamet mani', 'music/latvian/Aija Andrejeva - LAIME SI.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('BERMUDU DIVSTURIS', 'PONTA PEC', 'music/latvian/BERMUDU DIVSTURIS - PONTA PEC.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Dons', 'Ilgoties man nesanak', 'music/latvian/Dons - Ilgoties man nesanak.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Exact', 'Unlucky Loki', 'music/latvian/Exact - Unlucky Loki.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('MESA', 'Man nav bail', 'music/latvian/MESA - Man nav bail.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('MESA', 'Tuvak Tev', 'music/latvian/MESA - Tuvak Tev.mp3', 'latvian', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('MESA', 'Man nav bail', 'music/latvian/MESA - Man nav bail.mp3', 'latvian', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Urbanstep', 'Take Apart The Sky', 'music/latvian/Urbanstep - Take Apart The Sky.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Edavardi', 'Spoki', 'music/latvian/Edavardi - Spoki.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Rassell', 'Skrien cauri dzivei', 'music/latvian/Rassell - Skrien cauri dzivei.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Eliots', 'Carguru', 'music/latvian/Eliots - Carguru.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Markus Riva', 'Vienmer', 'music/latvian/Markus Riva - Vienmer.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Fakts', 'Karantinas Bluzs', 'music/latvian/Fakts - Karantinas Bluzs.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Markus Riva', 'Melns Vai Balts', 'music/latvian/Markus Riva - Melns Vai Balts.mp3', 'latvian', 2020);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('TAVS KAROGS', 'The Sound Poets', 'music/latvian/TAVS KAROGS - T-he Sound Poets.mp3', 'latvian', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Kreisais Krasts', 'Vardu Piegade', 'music/latvian/Kreisais Krasts - Vardu Piegade.mp3', 'latvian', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Aminata', 'Uz neatklatam zvaigznem', 'music/latvian/Aminata - Uz neatklatam zvaigznem.mp3', 'latvian', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Dzelzs Vilks', 'AIZLIEGUMI LIKUMI', 'music/latvian/Dzelzs Vilks - AIZLIEGUMI LIKUMI.mp3', 'latvian', 2021);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Martins Ruskis', 'Mes nepagursim', 'music/latvian/Martins Ruskis - Mes nepagursim.mp3', 'latvian', 2012);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Prata Vetra', 'Ko tu doma', 'music/latvian/Prata Vetra - Ko tu doma.mp3', 'latvian', 2012);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('GACHO', 'Stampa Gridu', 'music/latvian/GACHO - Stampa Gridu.mp3', 'latvian', 2012);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Prata Vetra', 'Lantern', 'music/latvian/Prata Vetra - Lantern.mp3', 'latvian', 2012);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('Audience Killers', 'The Runaway Kite', 'music/latvian/Audience Killers - The Runaway Kite.mp3', 'latvian', 2011);
INSERT INTO songs (song_author, song_name, song_path, song_genre, song_year) VALUES ('MELLENDIG', 'Say IT', 'music/latvian/MELLENDIG - Say It.mp3', 'latvian', 2012);