version: '3.4'
services:
  db:
    container_name: postgresql
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-p@ssw0rd}
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_DB:-project}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:${POSTGRES_PORT}
    env_file:
      - .env
    restart: unless-stopped
  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - PORT=${BACKEND_PORT}
    ports:
      - 9091:${BACKEND_PORT}
    env_file:
      - .env
    volumes:
      - ./backend:/usr/local/apps/backend
      - exclude:/usr/local/apps/backend/node_modules
    depends_on:
      db:
        condition: service_healthy
volumes:
  exclude:
  postgres-data: