version: '3.4'
services:
  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - PORT=${BACKEND_PORT}
    ports:
      - 9091:${BACKEND_PORT}
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/local/apps/backend
      # - /usr/local/apps/backend/node_modules
      - exclude:/usr/local/apps/backend/node_modules

volumes:
  exclude: