version: '3.4'
services:
  db:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-p@ssw0rd}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:${POSTGRES_PORT}
    env_file:
      - .env
    restart: unless-stopped
  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - PORT=${BACKEND_PORT}
    ports:
      - 9091:${BACKEND_PORT}
    env_file:
      - .env
    volumes:
      - ./backend:/usr/local/apps/backend
      - exclude:/usr/local/apps/backend/node_modules
    depends_on:
      - db  
volumes:
  exclude:
  postgres: